# Uncomment the next line to define a global platform for your project
# platform :ios, '10.0'

target 'ITS' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
pod 'FirebaseAuth'
pod 'FirebaseFirestore'
pod 'FirebaseStorage'
pod 'CocoaMQTT'
pod 'FirebaseDatabase'
pod 'TinyConstraints', '~> 4.0.0'
pod 'Gifu', '~> 3.2.0'
pod 'ColorSlider'
pod 'lottie-ios'
  # Pods for ITS

end
